### PR TITLE
remove use of Behaviour module and update tests

### PR DESCRIPTION
**Pull request by allyraza**
http://elixir-lang.org/docs/stable/elixir/Behaviour.html

### CODE REVIEW

**Comment by fishcakez** [comment]
Sorry `Connection` supports Elixir `~> 1.0` and `@callback is ~> 1.1` so we will keep using the `Behaviour` module.

Can you explain the test changes?

**Comment by allyraza** [comment]
when I ran the test suit it was failing so made the necessary changes, don't you think we should bump elixir version to 1.1 since 1.3 is already out.

**Comment by fishcakez** [comment]
> when I ran the test suit it was failing so made the necessary changes

@allyraza could you let me know what versions of OTP/Elixir caused the tests to fail? The output will be different depending on many possible combinations of OTP and Elixir so likely we are missing some combinations. I know we miss the OTP 17.0-17.2 combination and will likely fail tests there :(.

>  don't you think we should bump elixir version to 1.1 since 1.3 is already out.

What do we gain from setting 1.1 as a minimum requirement? Our current code is still okay for 1.3, and even current 1.4.0-dev. If we dropped support for 1.0 that would mean a breaking change and bumping this library to `2.0`.

**Comment by fishcakez** [comment]
Closing in favour of #9.

**Pull request closed without merging**
