### PR TITLE
Fix default callback definitions as state actually is used

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by fishcakez** [comment]
Thanks @lexmag, ill bump to `1.0.1` so we don't get a warning once `1.1.0` is out.

**Comment by lexmag** [comment]
Great! As you see it's not about warning though, it gives `CompileError`.
Probably it worth to have in test a `Sample` module that uses `Connection` thus we are sure that it'll compiles with `__using__`.

**Comment by lexmag** [comment]
Would you like a PR with test? :smile:

**Comment by fishcakez** [comment]
Oh I misread the diff thinking we were using `_state`, sure please a PR.

**Pull request merged**
