### PR TITLE
Get rid of "use Behaviour"

### PR DESCRIPTION
**Pull request by gmile**
Per https://github.com/elixir-lang/elixir/pull/5037

### CODE REVIEW

**Comment by lexmag** [comment]
(Gen:bowtie:)Connection still supports Elixir v1.0 so we can't remove `use Behaviour` yet.

**Comment by gmile** [comment]
@lexmag makes sense, should have looked in `mix.exs` first. I guess same applied to https://github.com/elixir-ecto/postgrex/pull/223 then.

Should I close this one, or let it keep hanging? I suppose it'll take a while before 1.0 gets dropped and this PR gets merged

**Comment by lexmag** [comment]
Yeah, same applies to Postgrex PR as well. I'd close the PR as it indeed will take some time before 1.0 gets dropped.

**Comment by josevalim** [comment]
I would say this is fine because using `@callback` is backwards compatible and it will work on Elixir v1.0.

**Comment by lexmag** [comment]
@josevalim then we lose the docs and other important metadata, which quite important for Connection.

**Comment by josevalim** [comment]
We only lose those if you try to generate the docs using Elixir
v1.0 version, which is not even supported by ExDoc anymore. Between that
and getting a warning in Elixir v1.0, I would much rather merge this.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
Closing as #8 already exists. We will need to make test changes to handle newer versions of elixir/erlang.

**Comment by fishcakez** [comment]
`v1.0.4` is out which requires Elixir 1.2. This fixes a bug where OTP 17.0-17.3 could log internal state and so is only a patch release.

**Pull request merged**
