### PR TITLE
Add test for `__using__` macro

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by fishcakez** [comment]
If we're going to have a test shall we test the callbacks work as intended? I.e. assert that `Sample.connect/2` exits with `{:bad_connect, arg}` etc? We can call the callbacks directly, no need to use a `Connection` process.

**Comment by fishcakez** [comment]
I'll do it :), thanks for catching this,

**Comment by lexmag** [comment]
Yeah, let's add more tests. I've been about to start. :smile:

**Comment by fishcakez** [comment]
Add more tests in https://github.com/fishcakez/connection/commit/9ce1b4c36b4fd9354aec90cfb081724162b8c109

**Pull request merged**
